steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "enter 1 bash command per line"
          ls -la
          gcloud version
          echo 'bash - substitution variables'
          env
          echo '_COMMIT_MESSAGE: ' $_COMMIT_MESSAGE



logsBucket: 'gs://buildlogsbucket'

options:
  logging: CLOUD_LOGGING_ONLY
  #logging: GCS_ONLY
